#!/bin/bash -e
host=$1
port=${2:-25565}
now=$(date +'%Y-%m-%dT%H:%M:%S')
clientlog=${3:-logs/$now.client.log}
serverlog=${4:-logs/$now.server.log}
[ "$(dirname "$clientlog")" = logs ] || [ "$(dirname "$serverlog")" = logs ] && mkdir -p logs
coproc { tee "$serverlog"; }
exec 3<&${COPROC[0]} 4>&${COPROC[1]}
nc -l 25565 <&3 | tee "$clientlog" | nc "$host" "$port" >&4
kill $COPROC_PID
